### ISSUE TITLE
Tests failing: no module named makedocco

### ISSUE THREAD

**Issue by koslambrou** [RDFLib/pyLODE#98] opened 2020-08-24 13:36 UTC
In current master branch, the tests with `pytest` are failing.

Steps to reproduce in GNU/Linux:

```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pytest
```

This produces the following output:

```
======================================== test session starts ========================================
platform linux -- Python 3.8.1, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/.../git/pyLODE
collected 1 item / 2 errors

============================================== ERRORS ===============================================
____________________ ERROR collecting pylode/tests/test_ont_html_description.py _____________________
ImportError while importing test module '/home/.../git/pyLODE/pylode/tests/test_ont_html_descriptio
n.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/zv2wr03613fbqng9rvalrsh8yrrjbncw-python3-3.8.1/lib/python3.8/importlib/__init__.py:127: in
 import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pylode/tests/test_ont_html_description.py:1: in <module>
    from makedocco import MakeDocco
E   ModuleNotFoundError: No module named 'makedocco'
____________________________ ERROR collecting pylode/tests/test_skos.py _____________________________
ImportError while importing test module '/home/.../git/pyLODE/pylode/tests/test_skos.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/zv2wr03613fbqng9rvalrsh8yrrjbncw-python3-3.8.1/lib/python3.8/importlib/__init__.py:127: in
 import_module
    return _bootstrap._gcd_import(name[level:], package, level)
pylode/tests/test_skos.py:1: in <module>
    from makedocco import MakeDocco
E   ModuleNotFoundError: No module named 'makedocco'
====================================== short test summary info ======================================
ERROR pylode/tests/test_ont_html_description.py
ERROR pylode/tests/test_skos.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================= 2 errors in 0.33s =========================================
```

**Comment by nicholascar** [comment] 2020-08-25 03:45
Ooops, tests were out-of-date regarding file locations. I've fixed this so try after pulling.

**Comment by koslambrou** [comment] 2020-08-25 10:10
Great, it works. Thanks!

**Comment by nicholascar** [comment] 2020-08-25 11:13
Yes, but there aren't really many good tests and some of the tests just produce outputs but don't really assert things in the way that will allow them to be used in proper build tools so please feel free to contribute more tests!

I'll close this now since the issue is resolved.

**Closed by nicholascar** 2020-08-25 11:13 UTC
