### ISSUE TITLE
Any reason why fragment identifiers are not generated from the local name of the class/property's URI?

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/pyLODE#95] opened 2020-08-19 23:32 UTC
For example, looking at the small datatype vocabulary, we can see the class [QuantitativeMeasure's](https://raw.githack.com/AGLDWG/datatype-ont/master/html/datatype.html#quantitativemeasure) fragment ID generated by pylode is `quantitativemeasure`, which is the value of the label. I personally think it makes more sense to use the local name of the URI so that the value would be `QuantitativeMeasure` for the fragment ID. 

If the fragment IDs are generated from the local name, then it makes it possible to do things with redirects like http://linked.data.gov.au/def/datatype/QuantitativeMeasure -> http://linked.data.gov.au/def/datatype#QuantitativeMeasure.

Thoughts?

**Comment by graybeal** [comment] 2020-08-20 01:42
Making that change also meets the expectations of most users for what a fragment identifier is meant to be, doesn't it? Because the label can be literally anything, but the fragment identifier is almost always used along the lines you've suggested, as far as I know.

**Comment by nicholascar** [comment] 2020-08-24 11:52
This is essentialyl a duplicate of #86 I think I have a way forward here: there were a couple of issues about doing the "obvious" thing but I've got a plan now, as articulated in #86, so I'm shutting this down to focus the discussion there.

**Closed by nicholascar** 2020-08-24 11:52 UTC
